name: ips_dashboard
services:
  api:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app              # ✅ Ajout clé
    volumes:
      - ./app:/app
    working_dir: /app
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ipsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard_app
    ports:
      - "8050:8050"
    depends_on:
      - db
    volumes:
      - ./dashboard:/dashboard

volumes:
  pgdata:
